plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
markdown: GFM
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - pt.md
  - README.md
  - LICENSE
name: ""
title: null
