plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
markdown: GFM
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - resume.pt.md
  - README.md
  - LICENSE
title: null
description: [My resume/Meu currículo]
