plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
markdown: GFM
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - README.md
  - LICENSE
  - CERTIFICATES.pt.md
  - CERTIFICATES.en.md
title: [My CV]
description: [My resume - Felipe Miguel Nery Lunkes]
