plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
markdown: GFM
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - pt.md
exclude:
  - README.md
  - LICENSE
  - AUTHORS
  - CREDITS
  - VERSION
name: ""
title: null
